name: Deploy layout- & content-elements-examples to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "layout-examples/**"
      - "content-elements-examples/**"
      - ".github/workflows/examples-pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-examples"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Prepare dist & convert Markdown
        run: |
          rm -rf dist
          mkdir -p dist/layout-examples dist/content-elements-examples

          # 1) Kopiere alle Quellen
          rsync -a layout-examples/ dist/layout-examples/ || true
          rsync -a content-elements-examples/ dist/content-elements-examples/ || true

          # 2) Konvertiere alle .md -> .html (parallel in-place in dist)
          find dist/layout-examples dist/content-elements-examples -type f -iname "*.md" | while read -r f; do
            html="${f%.md}.html"
            pandoc "$f" -f markdown -t html5 -s -o "$html"
          done

          # 3) .nojekyll, damit Pages nichts umbaut
          touch dist/.nojekyll

          # 4) index.html mit Linkliste NUR auf HTML/HTM
          cat > dist/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>Examples</title>
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <style>
            body{font:16px/1.5 system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:2rem;max-width:72ch}
            h1{margin:0 0 1rem}
            ul{padding-left:1.2rem}
            a{word-break:break-word}
            code{background:#f6f8fa;padding:.1rem .3rem;border-radius:.25rem}
          </style>
          <h1>Examples</h1>
          <p>Gerenderte Beispiele aus <code>layout-examples/</code> und <code>content-elements-examples/</code>. Markdown wurde in HTML konvertiert.</p>
          <ul>
          HTML
          find dist/layout-examples dist/content-elements-examples -type f \( -iname "*.html" -o -iname "*.htm" \) | sed 's#^dist/##' | sort | while read -r f; do
            esc="$(printf '%s\n' "$f" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')"
            echo "<li><a href=\"${esc}\">${esc}</a></li>" >> dist/index.html
          done
          echo "</ul>" >> dist/index.html

          # 5) 404 → zurück zur Übersicht
          cat > dist/404.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>Not Found</title>
          <meta http-equiv="refresh" content="0; url=./index.html">
          <p>Seite nicht gefunden. <a href="./index.html">Zur Übersicht</a>.</p>
          HTML

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
