name: Deploy layout- & content-elements-examples to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "layout-examples/**"
      - "content-elements-examples/**"
      - "content-elements/**"
      - "layouts/**"
      - "frontend/**"
      - ".github/workflows/examples-pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-examples"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dist
        run: |
          rm -rf dist
          mkdir -p dist
          rsync -a --exclude 'dist/' --exclude '.git/' ./ dist/
          touch dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
